---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: cs3org/cs3apis:latest
  environment:
    SSH_KEY:
      from_secret: deploy_key
  commands:
    # See https://github.com/drone/drone/issues/2692
    # write the ssh key to disk
    - mkdir /root/.ssh
    - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa

    # add github to known hosts
    - touch /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/known_hosts
    - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
    - make all

- name: publish-docker
  pull: always
  image: plugins/docker
  settings:
    repo: cs3org/cs3apis
    tags: latest
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
